### ISSUE TITLE
shorse?

### ISSUE THREAD

**Issue by y-samy** [YusufEmad04/shorse#1]
Shorse shorse shorse shorse, shorse shorse, shorse shorse shorse. Shorse, shorse shorse shorse - shorse shorse - shorse shorse shorse shorse shorse; shorse shorse shorse shorse shorse shorse shorse. Shorse shorse shorse shorse.
![image](https://github.com/YusufEmad04/shorse/assets/51068469/c8841178-9698-46a2-8113-51b4518eb39f)

**Comment by YusufEmad04** [comment]
shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse shorse

**Comment by abdelrahmangasser555** [comment]
shorse shorse shoog gasser
